module.exports = {
    stopwords:[
        "en",
        "som",
        "i stand",
        "handle om",
        "ovenfor",
        "i henhold",
        "tilsvarende",
        "på tvers",
        "faktisk",
        "etter",
        "etterpå",
        "en gang til",
        "imot",
        "Er ikke",
        "alle",
        "tillate",
        "tillater",
        "nesten",
        "alene",
        "langs",
        "allerede",
        "også",
        "selv om",
        "alltid",
        "er",
        "blant",
        "Blant",
        "En",
        "og",
        "en annen",
        "noen",
        "enhver",
        "uansett",
        "hvem som helst",
        "hva som helst",
        "uansett",
        "uansett",
        "hvor som helst",
        "fra hverandre",
        "Virke",
        "sette pris på",
        "passende",
        "Er",
        "Ikke",
        "rundt",
        "som",
        "Side",
        "spørre",
        "Spør",
        "assosiert",
        "på",
        "tilgjengelig",
        "borte",
        "forferdelig",
        "B",
        "være",
        "ble til",
        "fordi",
        "bli til",
        "blir",
        "ferd med å bli",
        "Vært",
        "før",
        "Forhånd",
        "bak",
        "å være",
        "tro",
        "under",
        "ved siden av",
        "i tillegg",
        "beste",
        "bedre",
        "mellom",
        "bortenfor",
        "både",
        "kort",
        "men",
        "av",
        "C",
        "kom igjen",
        "c",
        "Kom",
        "kan",
        "Kan ikke",
        "kan ikke",
        "Cant",
        "årsaken",
        "fører til",
        "sikker",
        "sikkert",
        "Endringer",
        "helt klart",
        "Co",
        "Com",
        "komme",
        "Kommer",
        "angående",
        "Derfor",
        "ta i betraktning",
        "med tanke på",
        "inneholde",
        "inneholder",
        "Inneholder",
        "tilsvarende",
        "Kunne",
        "Kunne ikke",
        "kurs",
        "for tiden",
        "D",
        "helt sikkert",
        "Beskrev",
        "til tross for",
        "Gjorde",
        "Ikke",
        "forskjellig",
        "gjøre",
        "gjør",
        "Ikke",
        "driver med",
        "Ikke",
        "Ferdig",
        "ned",
        "Nedover",
        "under",
        "E",
        "Hver",
        "Edu",
        "Eksempel",
        "åtte",
        "enten",
        "ellers",
        "Andre steder",
        "nok",
        "fullstendig",
        "spesielt",
        "Et",
        "etc",
        "til og med",
        "noensinne",
        "hver",
        "alle",
        "Alle",
        "alt",
        "overalt",
        "Ex",
        "nøyaktig",
        "eksempel",
        "unntatt",
        "F",
        "langt",
        "få",
        "femte",
        "først",
        "fem",
        "fulgte",
        "følgende",
        "Følger",
        "til",
        "tidligere",
        "tidligere",
        "Frem",
        "Fire",
        "fra",
        "lengre",
        "Dessuten",
        "G",
        "få",
        "Får",
        "får",
        "Gitt",
        "Gir",
        "gå",
        "Går",
        "går",
        "Borte",
        "Fikk",
        "Fått",
        "hilsener",
        "H",
        "hadde",
        "Hadde ikke",
        "Skjer",
        "neppe",
        "Har",
        "Har ikke",
        "ha",
        "Har ikke",
        "Ha",
        "han",
        "Han er",
        "Hallo",
        "hjelp",
        "Derav",
        "henne",
        "her",
        "Her er",
        "Heretter",
        "Herved",
        "Heri",
        "Hvorpå",
        "hennes",
        "Seg selv",
        "Hei",
        "ham",
        "han selv",
        "hans",
        "Hit",
        "Forhåpentligvis",
        "hvordan",
        "By omringet",
        "derimot",
        "Jeg",
        "Jeg vil",
        "jeg vil",
        "jeg er",
        "Jeg har",
        "dvs",
        "hvis",
        "Ignorert",
        "umiddelbar",
        "i",
        "Ettersom",
        "Inc",
        "faktisk",
        "indikerer",
        "Indikert",
        "Indikerer",
        "indre",
        "Utstrekning",
        "i stedet",
        "inn i",
        "Innover",
        "er",
        "Er ikke",
        "den",
        "Det ville",
        "Det vil",
        "det er",
        "det er",
        "seg selv",
        "J",
        "bare",
        "K",
        "beholde",
        "Holder",
        "Holdt",
        "vet",
        "Vet",
        "Kjent",
        "L",
        "siste",
        "i det siste",
        "seinere",
        "Siste",
        "Latterly",
        "minst",
        "mindre",
        "Lest",
        "la",
        "La oss",
        "som",
        "Likt",
        "sannsynlig",
        "litt",
        "se",
        "Ser",
        "utseende",
        "Ltd",
        "M",
        "hovedsakelig",
        "mange",
        "kan",
        "kan være",
        "meg",
        "mener",
        "i mellomtiden",
        "Bare",
        "kanskje",
        "mer",
        "Dessuten",
        "mest",
        "for det meste",
        "mye",
        "må",
        "min",
        "Meg selv",
        "N",
        "Navn",
        "Nemlig",
        "Nd",
        "nær",
        "nesten",
        "nødvendig",
        "trenge",
        "behov",
        "ingen",
        "aldri",
        "Likevel",
        "ny",
        "Neste",
        "ni",
        "Nei",
        "ingen",
        "ikke",
        "ingen",
        "ingen",
        "eller",
        "normalt",
        "ikke",
        "ingenting",
        "roman",
        "nå",
        "ingen steder",
        "O",
        "åpenbart",
        "av",
        "av",
        "ofte",
        "Åh",
        "Ok",
        "greit",
        "gammel",
        "på",
        "en gang",
        "en",
        "de",
        "bare",
        "videre til",
        "eller",
        "annen",
        "andre",
        "ellers",
        "burde",
        "våre",
        "Vår",
        "oss",
        "ute",
        "utenfor",
        "over",
        "alt i alt",
        "egen",
        "P",
        "bestemt",
        "særlig",
        "per",
        "kanskje",
        "Plassert",
        "vær så snill",
        "i tillegg til",
        "mulig",
        "antagelig",
        "sannsynligvis",
        "Gir",
        "Q",
        "Que",
        "ganske",
        "QV",
        "R",
        "heller",
        "Rd",
        "Re",
        "egentlig",
        "Rimelig",
        "angående",
        "uansett",
        "hilsen",
        "Relativt",
        "Henholdsvis",
        "Ikke sant",
        "S",
        "sa",
        "samme",
        "sag",
        "si",
        "ordtak",
        "sier",
        "sekund",
        "for det andre",
        "se",
        "ser",
        "synes",
        "syntes",
        "Tilsynelatende",
        "virker",
        "Sett",
        "selv",
        "selv",
        "fornuftig",
        "sendt",
        "seriøs",
        "alvor",
        "Seven",
        "flere",
        "Skal",
        "hun",
        "bør",
        "Bør ikke",
        "siden",
        "seks",
        "så",
        "noen",
        "noen",
        "en eller annen måte",
        "Noen",
        "noe",
        "En gang",
        "noen ganger",
        "noe",
        "et sted",
        "snart",
        "unnskyld",
        "Spesifisert",
        "Angir",
        "Angi",
        "fortsatt",
        "under",
        "slik",
        "Sup",
        "sikker",
        "T",
        "t-tallet",
        "ta",
        "Tatt",
        "fortelle",
        "pleier",
        "Th",
        "enn",
        "takke",
        "Takk",
        "Thanx",
        "at",
        "Det er",
        "dvs",
        "de",
        "deres",
        "Deres",
        "dem",
        "dem selv",
        "deretter",
        "Derfra",
        "der",
        "det er",
        "deretter",
        "derved",
        "derfor",
        "Deri",
        "det er",
        "Derpå",
        "disse",
        "de",
        "De hadde",
        "De vil",
        "De er",
        "De har",
        "synes at",
        "tredje",
        "dette",
        "grundig",
        "Grundig",
        "de",
        "selv om",
        "tre",
        "gjennom",
        "gjennom",
        "gjennom",
        "og dermed",
        "til",
        "sammen",
        "også",
        "Tok",
        "mot",
        "Mot",
        "Prøvd",
        "prøver",
        "Virkelig",
        "prøve",
        "Prøver",
        "to ganger",
        "to",
        "U",
        "Un",
        "under",
        "dessverre",
        "med mindre",
        "lite sannsynlig",
        "før",
        "Til",
        "opp",
        "på",
        "oss",
        "bruk",
        "Brukt",
        "nyttig",
        "bruker",
        "ved hjelp av",
        "som oftest",
        "UUCP",
        "V",
        "verdi",
        "diverse",
        "veldig",
        "Via",
        "Nemlig",
        "Vs",
        "W",
        "Ønsker",
        "Ønsker",
        "var",
        "Var ikke",
        "vei",
        "vi",
        "Vi hadde",
        "vi vil",
        "Vi er",
        "Vi har",
        "Velkommen",
        "vi vil",
        "Gikk",
        "Var",
        "Var ikke",
        "hva",
        "Hva er",
        "samme det",
        "når",
        "Hvorfra",
        "når som helst",
        "hvor",
        "hvor er",
        "Hvoretter",
        "Mens",
        "Hvorved",
        "Hvori",
        "Hvorpå",
        "hvor enn",
        "om",
        "hvilken",
        "samtidig som",
        "Dit",
        "hvem",
        "Hvem er",
        "Hvem",
        "hel",
        "hvem",
        "hvem sin",
        "Hvorfor",
        "vil",
        "villig",
        "skulle ønske",
        "med",
        "innenfor",
        "uten",
        "Vil ikke",
        "lure på",
        "Ville",
        "Ville",
        "Ikke ville",
        "X",
        "Y",
        "ja",
        "ennå",
        "du",
        "Du",
        "Du vil",
        "Du er",
        "Du har",
        "din",
        "din",
        "deg selv",
        "dere",
        "Z",
        "null"
    ]
};
